/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

export type ActivityType = 'user' | 'publication' | 'comment' | 'review';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityType = {
    user: 'user' as ActivityType,
    publication: 'publication' as ActivityType,
    comment: 'comment' as ActivityType,
    review: 'review' as ActivityType,
};
