/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */
import type { Publication } from './publication';
import type { ReviewStatus } from './reviewStatus';
import type { User } from './user';

export interface Review {
    publication: Publication;
    owner: User;
    createdAt: number;
    updatedAt: number;
    status: ReviewStatus;
    id: string;
}
