/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

export type UserRole = 'default' | 'moderator' | 'administrator';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
    default: 'default' as UserRole,
    moderator: 'moderator' as UserRole,
    administrator: 'administrator' as UserRole,
};
