workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    
stages:
  - install
  - quality
  - test

install:
  image: node:14.17.0
  stage: install
  script:
    - yarn install
    - yarn transform-yaml
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/
      - swagger.json
linting:
  extends: install
  stage: quality
  script:
    - yarn lint

tests:
  extends: install
  stage: test
  script:
    - yarn test


