/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

export type DeletionResponseResponseStatus = 'ok';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletionResponseResponseStatus = {
    ok: 'ok' as DeletionResponseResponseStatus,
};
