/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

export type GetCommentId200Status = 'ok';

export const GetCommentId200Status = {
    ok: 'ok' as GetCommentId200Status,
};
