/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */
import type { GetPublicationUsernameNameRevisionAll200Status } from './getPublicationUsernameNameRevisionAll200Status';
import type { FileResponse } from './fileResponse';

export type GetPublicationUsernameNameRevisionAll200 = {
  status: GetPublicationUsernameNameRevisionAll200Status;
  entries: FileResponse[];
};
