/**
 * Generated by orval v6.5.3 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */
import type { GetPublicationUsernameNameRevision200Status } from './getPublicationUsernameNameRevision200Status';
import type { Publication } from './publication';

export type GetPublicationUsernameNameRevision200 = {
  status: GetPublicationUsernameNameRevision200Status;
  publication: Publication;
};
