/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

export type GetUserUsernameFollow200Status = 'ok';

export const GetUserUsernameFollow200Status = {
    ok: 'ok' as GetUserUsernameFollow200Status,
};
