/**
 * Generated by orval v6.6.0 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */
import type { CommentAnchor } from './commentAnchor';

export interface SgComment {
  id: number;
  replying?: number;
  filename?: string;
  anchor?: CommentAnchor;
  contents: string;
  author: string;
  thread: number;
  postedAt: number;
}
