/**
 * Generated by orval v6.6.0 🍺
 * Do not edit manually.
 * Iamus API
 * This is a REST API for interfacing with Iamus. This API provides endpoints for interacting with user information, submissions, and reviews.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The username can either be the actual username or the user's email.
 */
export interface UserLogin {
  username: string;
  password: string;
}
